[project]
name = "umkm-alliance"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.umkm-alliance-3]
path = "contracts/umkm-alliance.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }